### ISSUE TITLE
Should we include lib++ and libc++abi here?

### ISSUE THREAD

**Issue by sbc100** [CraneStation/wasi-libc#70]
Right now we build them separately on top of this repo (at least on the wasm waterfall).

It seems that we should be including them if we want to continue to call this "sysroot".  Otherwise we should rename this to "wasi-libc".. since its just one component of a sysroot.

If we do want to include them here I suggest we do so via git submodule of `https://github.com/llvm-mirror/libcxx` etc..  since AFAICT they don't need any modification.

**Comment by sunfishcode** [comment]
It's a good question. The Rust WASI toolchain also uses this wasi-sysroot, and doesn't need it to include a libc++ or libc++abi, which suggests we keep them separate. And I agree, in that case "wasi-libc" is a better name for this repo. Since we're already discussing renaming it as part of the discussion of [where this will live](https://github.com/WebAssembly/reference-sysroot/pull/11), it may make sense to rename "sysroot" to "libc" at that time too.

[wasi-sdk](https://github.com/CraneStation/wasi-sdk) is a repo which pulls in wasi-sysroot, libc++, libc++abi, compiler-rt, llvm, and clang, [all as plain git modules](https://github.com/CraneStation/wasi-sdk/tree/master/src), which sounds like it might be closer to what you want here. Would it make sense to switch the wasm waterfall to use wasi-sdk instead of wasi-sysroot directly?

The wasi-sdk git module points to the LLVM 8.0 release branch, while iirc the waterfall uses LLVM master. But you can tell the wasi-sdk Makefile to use a different LLVM, and it works with LLVM master.

**Comment by sbc100** [comment]
SGTM wrt to moving and renaming this repo.  I also agree that keeping this repo scoped down is a good idea.

I think I'll open a separate issue discuses what we want to do about the current overlap between the waterfall and the wasi-sdk.

**Comment by sunfishcode** [comment]
The repo is now renamed wasi-libc; moving it is being discussed elsewhere. I think we're in agreement to not include libc++ or libc++abi here, so we can close this issue.
