### ISSUE TITLE
realpath in stdlib.h but not in library

### ISSUE THREAD

**Issue by binji** [CraneStation/wasi-libc#81]
I assume we won't have `realpath` for WASI MVP, is that correct? It seems to included in `stdlib.h`.

**Comment by sunfishcode** [comment]
Yeah, WASI doesn't have absolute paths, so the standard `realpath` doesn't fit. I filed https://github.com/CraneStation/wasi-libc/pull/82 to remove the declarations.

That said, besides making paths absolute, `realpath` also resolves symbolic links, resolves `..` and `.` paths, and trims redundant `/` characters. We could conceivably have a `realpath` which does those things and maybe also resolves relative paths to be rooted at `.`, which might be enough for some use cases.

**Comment by sbc100** [comment]
It doesn't have absolute paths at the syscall layer, but doesn't it kind of emulate them in libpreopen?  I mean if the concept of PWD exists then can't realpath just use getcwd() to construct an abspath?

**Comment by sunfishcode** [comment]
We don't currently have `getcwd` either :-). libpreopen maps from absolute path to base + relative path, which isn't enough to do `getcwd`.

Should we add a `getcwd`? It does leak information about the host, and we can't easily virtualize or remap it because the main purpose is to get a string that you can send to another process or serialize out somewhere to be read by the outside world, so it has to reflect the actual host path name.

**Comment by pchickey** [comment]
I think we should encourage the programs that require these sort of absolute path functions to implement them totally in userland, if possible. I wouldn't want to expose the host's "real" cwd at all, but it should be possible to define these functions such that it always pretends to be under `/home/wasi` or something, right?

**Comment by sbc100** [comment]
No, I'm not talking about exposing the real host cwd.   But we can build cwd in userspace based on the pre-opened root fd can't we?   I'm surprised libpreopen doesn't do this already.  Wouldn'tit be as simple as doing:  base + global_cwd + relative? 

I don't understand what you mean about sending the string to the outside world.  Paths only make sense within a given module, right?  Or at least within modules that shared the same virtualized view of the filesystem.

**Comment by binji** [comment]
Right, I'd imagine it would be similar to running in a chroot.

**Comment by sunfishcode** [comment]
The original issue here is fixed in a4136500132759467a4241b1251dc25c0ca30ab3; we no longer declare `realpath`.

If anyone's interested in introducing a concept of a cwd, even without exposing the host cwd, we'd need new WASI support, so we should discuss this in [the WASI issue tracker](https://github.com/WebAssembly/WASI/issues).
