### ISSUE TITLE
Question: how are the WASI API pointer parameters boundary checked and converted to native address

### ISSUE THREAD

**Issue by Kevin0626** [CraneStation/wasi-libc#87]
Hi, according to my understanding about the WASM spec, the two steps in the subject must be executed during the runtime serving a WASI call. I traced it down to https://github.com/CraneStation/wasmtime/blob/master/wasmtime-wasi/src/syscalls.rs and got lost. I have no knowledge about Rust programming yet, so I want to ask for any quick answer. Probably I should plan some time for learning Rust.. thanks..

**Comment by kubkon** [comment]
Hey! Yeah, learning some Rust might be a good idea since we're striving to have `wasmtime` as well as the syscalls lib written purely in Rust. Anyhow, the crate you've arrived at used to be a wrapper around C implementation of the syscalls (now renamed to [wasmtime-wasi-c](https://github.com/CraneStation/wasmtime/tree/master/wasmtime-wasi-c)), and now it's a wrapper around a Rust implementation in the form of a [wasi-common](https://github.com/cranestation/wasi-common) library.

In terms of decoding pointers and general memory management, the module you are looking for can be found here [memory.rs](https://github.com/CraneStation/wasi-common/blob/master/src/memory.rs). It might be useful to actually grab a copy of `wasmtime`, compile it and run some example Wasm with trace logging on:

```
RUST_LOG=wasi_common=trace wasmtime -d some_binary.wasm
```

You should get output similar to that found [here](https://github.com/kubkon/rust-wasi-tutorial/blob/master/README.md#bonus-exploring-the-syscalls). Hope that helps! :-)

**Comment by Kevin0626** [comment]
Thank you for the guides @kubkon
